### ISSUE TITLE
App.config/settings compatibility

### ISSUE THREAD

**Issue by nblumhardt** [sonicjolt/serilog-sinks-rabbitmq#1]
https://github.com/sonicjolt/serilog-sinks-rabbitmq/blob/master/src/Serilog.Sink.RabbitMq/LoggerConfigurationRabbitMqExtension.cs#L21

Serilog's app settings support needs an overload of this method that accepts each parameter individually.

**Comment by sonicjolt** [comment]
I'm not sure how to fix this. It sounds like something that needs to be done in the Serilog repo ?

What can I do to solve it ?

**Comment by nblumhardt** [comment]
No, fixing it just entails adding an extra method in `LoggerConfigurationRabbitMQExtension` that accepts individual parameters instead of the one big configuration object. If you have a look at e.g. the MongoDB sink you'll see this pattern in action.

**Comment by sonicjolt** [comment]
Added overload of Extension method.

Believe this fixes the issue
