### ISSUE TITLE
Unavailable broker crashes the application

### ISSUE THREAD

**Issue by vidarkongsli** [sonicjolt/serilog-sinks-rabbitmq#18]
The plugin generally works great. However, if the broker is unavailable during logging initialization or during operation, it seems to break the application. (Exception from the RabbitMQ client is not handled inside the sink). Is there any advise on how to handle this?

**Comment by sonicjolt** [comment]
Thanks for that. I'll look into it after the holidays!

**Comment by sonicjolt** [comment]
re-created in more general issue #20 

Closing this one.
