### ISSUE TITLE
Structured message properties/JSON formatting

### ISSUE THREAD

**Issue by nblumhardt** [sonicjolt/serilog-sinks-rabbitmq#2]
https://github.com/sonicjolt/serilog-sinks-rabbitmq/blob/master/src/Serilog.Sink.RabbitMq/Sinks/RabbitMq/RabbitMqMessage.cs#L22

Even if JSON formatting is used, this will end up being JSON-string-within-JSON, so not super consumable - in general most sinks choose to either support JSON only or text only. It's not incorrect to pass an `ITextFormatter` through from the configuration method, but where this is done it's generally the flat output formats like console/file that do it.

**Comment by sonicjolt** [comment]
This is actually a dead class, and will be removed.

**Comment by sonicjolt** [comment]
Gone.
