### ISSUE TITLE
Configuration for error handling if rabbitmq instance is not available.

### ISSUE THREAD

**Issue by sonicjolt** [sonicjolt/serilog-sinks-rabbitmq#20]
It must be possible to specify how the RabbitMQ sink should react to a missing rabbitmq instance.

**Comment by vidarkongsli** [comment]
Have you had any time to look into this.
I believe this could be easily achieved by inheriting from `PeriodicBatchingSink` as described here: https://github.com/serilog/serilog/wiki/Reliability

Even though the RabbitMQ does not provide any batch writing, it would benefit from the reliability featured built in to Serilog.
For example: 
```c-sharp
public class RabbitMQSink : PeriodicBatchingSink
    {
        private readonly ITextFormatter _formatter;
        private readonly IFormatProvider _formatProvider;
        private readonly RabbitMQClient _client;

        public RabbitMQSink(RabbitMQConfiguration configuration,
            ITextFormatter formatter,
            IFormatProvider formatProvider) : base(configuration.BatchPostingLimit, configuration.Period)
        {
            _formatter = formatter ?? new RawFormatter();
            _formatProvider = formatProvider;
            _client = new RabbitMQClient(configuration);
        }

        protected override void EmitBatch(IEnumerable<LogEvent> events)
        {
            foreach (var logEvent in events)
            {
                var sw = new StringWriter();
                _formatter.Format(logEvent, sw);
                _client.Publish(sw.ToString());
            }
        }
    }
```
Would you perhaps considering accepting a PR?

**Comment by sonicjolt** [comment]
Sorry I have not been able to deal with this since I'm abroad right now. Please, if you have a solution ready for this, I'm very open to PR as your know as of today :-) And thanks alot.

**Comment by sonicjolt** [comment]
@vidarkongsli Thanks for the link about reliability. I completely agree that inheriting from PeriodicBatchSink is the way to go. If you have a PR, i'll be happy to merge it. Otherwise, I'll do it.

Thanks again

**Comment by sonicjolt** [comment]
I'm working on this

**Comment by vidarkongsli** [comment]
:+1:
