### ISSUE TITLE
NuGet compatibility with newer newer Serilog versions

### ISSUE THREAD

**Issue by greghoover** [sonicjolt/serilog-sinks-rabbitmq#28]
Currently depends on Serilog (>= 1.5.14 && < 2.0.0).
NuGet package won't install with the Serilog 2.2.1.

**Comment by jaredcnance** [comment]
Can you try it now? I'm using SeriLog 2.3.0

Make sure to reference v2.0.0 (https://www.nuget.org/packages/Serilog.Sinks.RabbitMQ/2.0.0)

**Comment by sonicjolt** [comment]
I believe we can close this.
