### ISSUE TITLE
Unnecessary Queue Name

### ISSUE THREAD

**Issue by jaredcnance** [sonicjolt/serilog-sinks-rabbitmq#29]
As far as I can tell [the queue name validation](https://github.com/sonicjolt/serilog-sinks-rabbitmq/blob/master/src/Serilog.Sinks.RabbitMQ/LoggerConfigurationRabbitMQExtension.cs#L88) is entirely unnecessary since we're publishing logs. I don't see where the queue name is used in the RabbitMQClient

This results in an unnecessary error for an unnecessary configuration value.

**Comment by sonicjolt** [comment]
This is correct. I search the repo, and didn't see anywhere it is used. It can be removed.
