### ISSUE TITLE
Encoding of string -> byte

### ISSUE THREAD

**Issue by nblumhardt** [sonicjolt/serilog-sinks-rabbitmq#3]
https://github.com/sonicjolt/serilog-sinks-rabbitmq/blob/master/src/Serilog.Sink.RabbitMq/Sinks/RabbitMq/RabbitMqClient.cs#L104

Is `System.Text.Encoding.UTF8.GetBytes()` an option here?

**Comment by sonicjolt** [comment]
Didn't know that one, saves us a bit of code. 

Done.
