### ISSUE TITLE
Dispose of RabbitMQSink and RabbitMQClient

### ISSUE THREAD

**Issue by syrotkin** [sonicjolt/serilog-sinks-rabbitmq#34]
If I understand correctly, `RabbitMQSink` and `RabbitMQClient` should implement `IDisposable` and be closed correctly when the user calls `Log.CloseAndFlush()` from the client application. I have a simple console application, which keeps hanging and cannot exit even after the call to `Log.CloseAndFlush`. On my machine, I tried implementing Dispose in said classes, and this seems to fix the hanging issue.

**Comment by sonicjolt** [comment]
That sounds correct - if you have a working example that reproduces this, please share :-)
