### ISSUE TITLE
Queue not longer part of RabbitMQConfiguration?

### ISSUE THREAD

**Issue by espenekvang** [sonicjolt/serilog-sinks-rabbitmq#35]
After upgrading to version 2.0 we notice that there is not longer a property called `Queue` on `RabbitMQConfiguration`. What is the correct property to use instead?

**Comment by jaredcnance** [comment]
@espenekvang this property was not being used by the library so we removed it. If you're trying to publish to a specific route, consider using the `RouteKey` parameter for direct or topic exchanges.

see Issue/#29 and PR/#30 for history behind this change.

**Comment by espenekvang** [comment]
Thanks!
