### ISSUE TITLE
Username should not be required

### ISSUE THREAD

**Issue by mribichich** [sonicjolt/serilog-sinks-rabbitmq#37]
Hi there, in our case we dont use username and password, but the library make us use one.
It shouldn't be necessary to specify one.

I could contribute if you wish

thanks!

**Comment by sonicjolt** [comment]
@mribichich I believe you can just enter empty strings in those two situations. Am I wrong ? If so, you're welcome to send a pull request

**Comment by mribichich** [comment]
Yes I enter empty strings, but it thrown me an exception saying that the
username was required

**Comment by jaredcnance** [comment]
this is the offending line: https://github.com/sonicjolt/serilog-sinks-rabbitmq/blob/master/src/Serilog.Sinks.RabbitMQ/LoggerConfigurationRabbitMQExtension.cs#L84

@mribichich please open a PR to address. Just to clarify, you do not authenticate with RabbitMQ? Or you authenticate with empty username/password combination?

**Comment by sonicjolt** [comment]
Isn't the solution so simple as to do a null-check on username, similar to 'password'. And then it's fixed ?

**Comment by mribichich** [comment]
Since is a close system, we don't authenticate. We dont need to worry about credentials in this case.

thanks, I'll do it later!

**Comment by sonicjolt** [comment]
Added PR for this: https://github.com/sonicjolt/serilog-sinks-rabbitmq/pull/38

**Comment by sonicjolt** [comment]
@mribichich I'm not certain that this will fix your issue though. But since I haven't tried it myself, I'm not certain. But [I found this post](http://stackoverflow.com/questions/36715087/rabbitmq-authentication-without-password), that talks about the same situation. And if you need to setup SSL/TLS, then I would argue it would be easier to just create a username/password.

**Comment by mribichich** [comment]
Thats weird. I already use the rabbitmq library for c# and I use it without
a username/password.

I dont think it should be a problem.

thanks!

**Comment by sonicjolt** [comment]
@mribichich That's cool. Do you have some code-samples that show how. Maybe we can improve this library using your code. Can you show us how you do it, then we can improve this library

**Comment by jaredcnance** [comment]
That kind of makes me question the implementation. Did you just not set the username/password? Did you ever change the username/password in the control panel? If you just haven't set them, then you most definitely are authenticating. You would just be using the default username/passwords:

> All factory properties have default values. The default value for a property will be used if the property remains unassigned prior to creating a connection:
>
>Username
>"guest"
>Password
>"guest"

http://www.rabbitmq.com/dotnet-api-guide.html

These are also the default credentials used by the RabbitMQ server. So, if you haven't explicitly changed them, then you are using the defaults.

**Comment by mribichich** [comment]
wow, I haven't seen that one. Thats new to me. So if that is how it works, then you are right, Its using the defaults one over the cover. I never seen a library using default credentials if you dont set them up.

I'll check with my app, changing the default username and password, and let you know what happends.

It thats the case, maybe this library can do the same thing

**Comment by sonicjolt** [comment]
Closing. Username is required.
