### ISSUE TITLE
How to Deserialize LogEvent

### ISSUE THREAD

**Issue by lommez** [sonicjolt/serilog-sinks-rabbitmq#42]
How can i deserialize the LogEvent that was serialize to the rabbit queue?

In the queue, i have a message just like this:

`{"Timestamp":"2017-09-28T20:34:04.6883220-03:00","Level":"Information","MessageTemplate":"{HostingRequestStarting:l}","RenderedMessage":"Request starting HTTP/1.1 GET http://localhost:5100/teste application/json ","Properties":{"Protocol":"HTTP/1.1","Method":"GET","ContentType":"application/json","ContentLength":null,"Scheme":"http","Host":"localhost:5100","PathBase":"","Path":"/teste","QueryString":"","HostingRequestStarting":"Request starting HTTP/1.1 GET http://localhost:5100/teste application/json ","EventId":{"Id":1},"SourceContext":"Microsoft.AspNetCore.Hosting.Internal.WebHost","RequestId":"0HL86P5K139GQ","RequestPath":"/teste"},"Renderings":{"HostingRequestStarting":[{"Format":"l","Rendering":"Request starting HTTP/1.1 GET http://localhost:5100/teste application/json "}]}}`

When i try to deserialize i got some exceptions.

**Comment by sonicjolt** [comment]
Hi lommez, I didn't see your issue. Is this still relevant ?

**Comment by lommez** [comment]
No.. thanks
