### ISSUE TITLE
Unable to specify multiple hostnames

### ISSUE THREAD

**Issue by Sharparam** [sonicjolt/serilog-sinks-rabbitmq#43]
The sink configuration only allows for specifying a single hostname (at least as far as I could see). We have a setup with multiple RabbitMQ servers where we'd like to connect to the first available.

RawRabbit supports this (to take another library around RabbitMQ as an example), by taking a list of Hostnames to connect to. Instead of setting the `HostName` property on `ConnectionFactory`, it passes that list of hostnames to RabbitMQ's `CreateConnection` method.

Would it be possible to add support for this in the sink? Perhaps a separate configuration property named in plural (`Hostnames`), which if specified makes the sink use multiple endpoints instead of a single one.

**Comment by sonicjolt** [comment]
This is certainly possible. Do you have time to write it yourself and make a PR ?
