### ISSUE TITLE
when QueueName is not exist

### ISSUE THREAD

**Issue by idefa** [sonicjolt/serilog-sinks-rabbitmq#44]
_model.QueueDeclare(_config.QueueName,
                                            durable: (int)_config.DeliveryMode == 2,
                                            exclusive: false,
                                            autoDelete: false,
                                            arguments: null);

**Comment by sonicjolt** [comment]
Im not sure what this is about. Please explain more precisely

**Comment by daghb** [comment]
@idefa: Remove QueueDeclare. A queue is not necessary for posting log elements, only Exchanges.
