### ISSUE TITLE
Project root namespace

### ISSUE THREAD

**Issue by nblumhardt** [sonicjolt/serilog-sinks-rabbitmq#5]
https://github.com/sonicjolt/serilog-sinks-rabbitmq/blob/master/src/Serilog.Sink.RabbitMq/Serilog.Sinks.RabbitMq.csproj#L10

If you set the root namespace to `Serilog` then the namespacing and folder structure will line up (avoiding things like `Serilog.Sinks.RabbitMQ.Sinks.RabbitMQ` appearing in a few files).

**Comment by sonicjolt** [comment]
Fixed. Renamed to 'Serilog'
