### ISSUE TITLE
[Question] - Unable to log properly & format issues

### ISSUE THREAD

**Issue by DineshPagadala** [sonicjolt/serilog-sinks-rabbitmq#53]
Hi Steffen,
**1) I had an issue with logging using serilog to rabbitmq.**
while publishing messages from serilog, rabbitmq receives a lot of unwanted messages with the actual messages.
how to store only the log message in rabbitmq.
Currently it saves like below:
{"Timestamp":"2018-08-27T12:11:30.4682719+05:30","Level":"Error","MessageTemplate":"Startup Logging!!"}
{"Timestamp":"2018-08-27T12:11:32.9674578+05:30","Level":"Information","MessageTemplate":"User profile is available. Using '{FullName}' as key repository and Windows DPAPI to encrypt keys at rest.","Properties":{"FullName":"C:\\Users\\Administrator\\AppData\\Local\\ASP.NET\\DataProtection-Keys","SourceContext":"Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager"}}
{"Timestamp":"2018-08-27T12:11:33.4844303+05:30","Level":"Information","MessageTemplate":"Entity Framework Core {version} initialized '{contextType}' using provider '{provider}' with options: {options}","Properties":{"version":"2.1.1-rtm-30846","contextType":"ConnectionsStoreModelContext","provider":"Microsoft.EntityFrameworkCore.Sqlite","options":"None","EventId":{"Id":10403,"Name":"Microsoft.EntityFrameworkCore.Infrastructure.ContextInitialized"},"SourceContext":"Microsoft.EntityFrameworkCore.Infrastructure"}}
{"Timestamp":"2018-08-27T12:11:33.6766514+05:30","Level":"Information","MessageTemplate":"Executed DbCommand ({elapsed}ms) [Parameters=[{parameters}], CommandType='{commandType}', CommandTimeout='{commandTimeout}']{newLine}{commandText}","Properties":{"elapsed":"8","parameters":"","commandType":"Text","commandTimeout":30,"newLine":"\r\n","commandText":"PRAGMA foreign_keys=ON;","EventId":{"Id":20101,"Name":"Microsoft.EntityFrameworkCore.Database.Command.CommandExecuted"},"SourceContext":"Microsoft.EntityFrameworkCore.Database.Command"}}

**2) my 2nd problem was i want to format my payload with additional params as below:**
{
	"AppId" : "18c57f8a-a8f5-4bd1",
	"AppName" : "some applicationName",
	"MessageType" : "Information",
	"Message" : "New Dashboard named 'dash 1' has been created by user dinesh.",
	"TimeStamp" : "2018-08-17T17:04:56",
}
but my currrent payload does't have id, name etc.

**Comment by sonicjolt** [comment]
@DineshPagadala Is this question still relevant, or can it be closed ?
