### ISSUE TITLE
Error at bootstrapping when rabbitMQ server is down

### ISSUE THREAD

**Issue by AndreRochaDev** [sonicjolt/serilog-sinks-rabbitmq#55]
Is there any way of handling the exception differently when there is an error connecting to the server at bootstrap level?

Thanks a lot

**Comment by huan086** [comment]
I'm working on fixing this

**Comment by AndreRochaDev** [comment]
Thanks a lot, i worked around it with a default configuration if it fails, but it would be cool if it would just ignore the sink if it does not work,

Thanks again!

**Comment by sonicjolt** [comment]
It sounds like an important issue to address. @huan086 I've requested that we have a talk about this on Gitter (see link on the front). I'll close this issue in a few days if I don't receive response. Not that I don't think it's important, but I am working towards cleaning up the repo.

**Comment by sonicjolt** [comment]
I'll remove this from milestone 3.0.0 as it is an improvement that can wait. Thereby not saying it's not important, because I think it is, but it's not pressing to become part of 3.0.0

**Comment by sonicjolt** [comment]
@huan086 Welcome back :-) - hope you had a good vacation
