### ISSUE TITLE
Define TLS12 and Policy in the sink

### ISSUE THREAD

**Issue by AndreRochaDev** [sonicjolt/serilog-sinks-rabbitmq#57]
Hello, is there any way to set up the sink with a TLS version  (eg: TLS12) and Policies,  instead of always using the default?

Thanks a lot
AR

**Comment by sonicjolt** [comment]
closed
https://github.com/sonicjolt/serilog-sinks-rabbitmq/pull/58
https://github.com/sonicjolt/serilog-sinks-rabbitmq/pull/52
