### ISSUE TITLE
License inconsistency

### ISSUE THREAD

**Issue by nblumhardt** [sonicjolt/serilog-sinks-rabbitmq#75]
Greetings! 👋 

The `LICENSE` here on the repository was [changed to GPL v3 a short while ago](https://github.com/sonicjolt/serilog-sinks-rabbitmq/pull/73/commits/69156cf59d61ff0f1ad298ffa2bee49a9420dee6). The [package on NuGet](https://www.nuget.org/packages/Serilog.Sinks.RabbitMQ/), ([because of this line in the CSPROJ](https://github.com/sonicjolt/serilog-sinks-rabbitmq/blob/master/src/Serilog.Sinks.RabbitMQ/Serilog.Sinks.RabbitMQ.csproj#L12)), is still listed as Apache 2.0.

There's a big difference between these licenses, so it would be great to get some clarity/make sure that the package information is correct.

Many users who are able to use the package under the earlier Apache 2.0 licensing possibly can't use it under GPL v3, so an announcement of the change somehow (README or issue tracker FAQ) might avoid some misunderstandings/confusion.

Hope this helps,
Nick

**Comment by sonicjolt** [comment]
Hi @nblumhardt thank you for making me aware of the inconsistency. We aim to follow Serilog, so I will adjust the current license back to Apache 2.0 asap.

**Comment by nblumhardt** [comment]
Great, thanks for the clarification @sonicjolt 🙂 👍

**Comment by sonicjolt** [comment]
Change applied, and will be released in 3.0.1
