### ISSUE TITLE
hostnames can not be empty

### ISSUE THREAD

**Issue by 596442958** [sonicjolt/serilog-sinks-rabbitmq#76]
.

**Comment by huan086** [comment]
Loading from configuration works

```cs
LoggerConfiguration loggerConfiguration = new LoggerConfiguration();
IConfigurationSection rabbitMqSection = configuration.GetSection("log:rabbitMq");
loggerConfiguration = loggerConfiguration
    .WriteTo.RabbitMQ((clientConfiguration, sinkConfiguration) =>
    {
        rabbitMqSection.Bind(clientConfiguration);
        sinkConfiguration.RestrictedToMinimumLevel = LogEventLevel.Warning;
    });
```

If you are configuring manually, then use Hostnames.Add

**Comment by tsvetelintsonev** [comment]
Hi, thank you for pointing this out. The configuration API in v3 has changed. I will update the readme.md later today . Until then maybe you can use the examples from this PR to set up the sink.

https://github.com/sonicjolt/serilog-sinks-rabbitmq/pull/69
