### ISSUE TITLE
Collect the Logs and publish them at once

### ISSUE THREAD

**Issue by abolfazlmohammadiseif** [sonicjolt/serilog-sinks-rabbitmq#88]
Hi,
I'm going to collect all the logs of each request (from the action method to maybe multiple services and classes) and at the end, send them all to RabbitMQ at once!

Is it possible? what is your suggestion?

Thanks alot

(I couldn't chose Question as label, there were just Bug and New Feature)

**Comment by sonicjolt** [comment]
That's is more or less what Serilog.Sinks.RabbitMq does out of the box. 
This library uses Serilog's EmitBatch, which bundles up a bunch of logs, and sends them asynchronously from time to time. 

Read about Serilog Periodic Batching: https://github.com/serilog/serilog-sinks-periodicbatching

**Comment by abolfazlmohammadiseif** [comment]
Do you know how to use it? 
I didn't find anyone using that.

**Comment by sonicjolt** [comment]
@abolfazlmohammadiseif No, what I mean is, Serilog.Sinks.RabbitMq already implements periodic batching.

**Comment by abolfazlmohammadiseif** [comment]
I Found how to config it. Thanks

**Comment by sonicjolt** [comment]
Happy to hear that. Good luck! :-)
